package com.revature.put_comment.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ForumNodes")
public class Comment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String owner;

    @DynamoDBAttribute
    private List<String> tags;

    @DynamoDBAttribute
    private String date_created;

    @DynamoDBAttribute
    private List<String> ancestors;

    @DynamoDBAttribute
    private int child_count;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String parent;

    @DynamoDBAttribute
    private String subject;

}